### ISSUE TITLE
psTransform error

### ISSUE THREAD

**Issue by shandley** [PratheepaJ/bootLong#2]
Hi!

I am having an issue with the psTransform ruction. Here is the command:

`ps.tr <- psTransform(ps0, main_factor = "Seroconversion")`

And this is the error:

Error in validObject(.Object) : invalid class “phyloseq” object: 
 Component taxa/OTU names do not match.
 Taxa indices are critical to analysis.
 Try taxa_names()

The taxa_names() function provides a list of ASV sequences.

Is there a preprocessing step I am missing to get from dada2/phyloseq data to psTransform?

Thanks!

Scott

**Comment by PratheepaJ** [comment]
Thanks for posting this issue.  This issue says that psTransform() could not be able to produce residual phyloseq and transformed counts phyloseq.
I have formatted R functions, and I got the same issue (another user also notified me).  
It must be related to archsinhlink function because I was able to run psTransform with log-link function.
I'm working around to fix it and will update you.

**Comment by PratheepaJ** [comment]
This issue has been fixed: I added column names and row names to ot_trans.

**Comment by shandley** [comment]
Awesome. Thanks for taking a look. We are incredibly interested in your approach and have several projects where your methods could apply. Amazing work here!

Unfortunately, I am still getting the same error after redownloading the new version.

Before digging in deeper I was curious about a few things that I just may not be clear on regarding the vignette. In the Merge by Subject section you spend some time explaining how to adjust and create a new PhyloSeq object called psm, however, that object doest appear anywhere else in the vignette. Can you explain to me what the utility of psm is?

My data follow the vignette very nicely through the plotSamplingSchedule, but am still stuck at pTransform. I attached an RDS of the data I am using in case you are interested. Essentially the only alteration we have made from your vignette is we are assessing "Seroconversion" instead of "Preterm". Other than that (and a bunch of additional metadata) everything should be in a very similar format.

 I will do some poking around of the psTransform function as well to see if I can sort out what is going on.

Many thanks!
[ps.RDS.zip](https://github.com/PratheepaJ/bootLong/files/2443784/ps.RDS.zip)

**Comment by PratheepaJ** [comment]
Thanks for the encouraging note.
Here are the answers to your questions:
1) I kept 'psm' if someone is interested in comparing DESeq2 results with merge-by-subject abundance.  Now, I removed 'psm' from vignette because it is not used for our method. 

2) I tried to look at the issue with the given phyloseq object but I don't get an rds file after unzipping.
Could you please zip and upload ps.rds file again?

**Comment by shandley** [comment]
Many thanks for looking into this. 

Not sure what's going on with the zip, so here is a DropBox link:

https://www.dropbox.com/s/ad3566oi5dty80j/ps.RDS?dl=0

No worries about sorting this on your end. Not meaning to have you do our work for us! But thought you might find it useful for troubleshooting in case other folks run into the same problem.

Thanks again

**Comment by PratheepaJ** [comment]
Thanks for sharing the data. This is definitely helpful because the package is in developing status.

I was able to work through the vignette: 
1) If you filter ASVs, make sure that rows are ASVs and columns are samples on otu_table of phyloseq object. Just tweak the code as follows:
if (dim(otu_table(ps))[2] != nsamples(ps)) {
        otu_table(ps) <- t(otu_table(ps))
    }
threshold <- .1
keep_asv <- apply(otu_table(ps),1,function(x){sum(x>0)}) > threshold*nsamples(ps)
ps <- prune_taxa(keep_asv,ps)

2) don't run 
#   Change the legend labels 
with the same arguments. 
If you would like to change the labels, run the following:
p.all <- lapply(p.all, function(x){
    x + scale_fill_discrete(name  ="Group", breaks=c("No", "Yes"), labels = c("NewNameforNo", "NewNameforYes"))
    })

3) When you run bootLongSubsampling, sampleID_var = "X.SampleID" 
 (I think 'SampleID' was changed to "X.SampleID" if you read the sample information using read.table.)

**Comment by PratheepaJ** [comment]
One more thing: 
### longitudinal data lag-plots
we can check only lag-plot up to the maximum number of lags in your data for each ASV. 
So I would suggest changing 8 to 6 or less,
lags <- as.list(seq(1, 6))

**Comment by shandley** [comment]
Awesome. Thank you so much. I have been able to run through the analysis. I am still learning about the output/settings, but this should be incredibly useful for us for several studies. Thanks again for all of your help!

**Comment by PratheepaJ** [comment]
Thanks for your input. I’ll update the vignette to give a better demonstration.

**Comment by PratheepaJ** [comment]
I'm closing this issue because I have fixed it. 
I also have updated the vignette to give more demonstration on the bootstrap method.
